name: autoPullRequest
on: 
  push:       
    branches-ignore:
      - 'main'          
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create pr 
        uses: peter-evans/create-pull-request@v6
        with:           
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "PR Automático desde rama: ${{ github.ref_name }}"
          body: "Pull Request generado automáticamente."
          reviewers: yahir63
          labels: automated-pr

      
      
